### ISSUE TITLE
Error loading index.html

### ISSUE THREAD

**Issue by KittyCatTech** [forknote/forknote-pool#17]
I am getting this error: "Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode" on line 317 in index.html

Please change this line form:
let title = $(".navbar-brand").text();
to
var title = $(".navbar-brand").text();

**Comment by pmitchev** [comment]
Hey mate,
Thank you for your contribution.
You can make pull requests anytime by the way if you have a fix for a bug.

**Comment by pmitchev** [comment]
Fixed in this commit:
https://github.com/forknote/forknote-pool/commit/03dfe04e88d5faf8889ae3d850b24804a3d891d8
