### ISSUE TITLE
forknote-pool running / no update on website

### ISSUE THREAD

**Issue by cycleworm** [forknote/forknote-pool#38]
Hi, 

my forknote-pool is up and running. One miner is already connected. based on the log of the pool everything looks good. no errors. but i do not get updates (hashrate, blockchain infos, ... ) on the website.

![image](https://user-images.githubusercontent.com/493769/32352380-4d1bcc96-c021-11e7-943a-0b18b4f9077a.png)

Any advices what could be wrong in the config?

**Comment by cycleworm** [comment]
i am not sure which configs have to be changed in the pool/website/config.js 
and in the pool/config.json to ensure proper data transfer between the pool and the website.

can anybody guide me in the right direction? thanks a lot

**Comment by cycleworm** [comment]
silly mistake from my side. forgot to add http:// in my config file. 
*/pool/website/config.js

![image](https://user-images.githubusercontent.com/493769/32381713-ab167e3a-c0b3-11e7-9161-cbf27271ffe5.png)

stats are getting now updated on the website 👍

**Comment by hongbaoblockchain** [comment]
@cycleworm Do u need to use external ip im trying on local machine and no go
