### ISSUE TITLE
making payments as paid manually?!

### ISSUE THREAD

**Issue by theraw** [forknote/forknote-pool#39]
Hello.
I'm running one pool where is only me and one of my friends mining and i haven't setup automatic payments not because i won't but i wasn't able to set it up wasn't working. 

so as there is only me and my friend i've send payments manually to him and i reset redis stats once per week. 

But example when i want to reset the pool i will need to leave just 1 miner till pending blocks gets mined but as of now we're getting alot of blocks 
![image](https://user-images.githubusercontent.com/32969774/32372254-fd3695ba-c08b-11e7-98fb-c0bd53be9a4b.png)
and to reset the pool it will take me 2-3 days :confused: so i will like to know if there's anyway to make payments as paid manually?!

Thanks.

**Comment by cycleworm** [comment]
why couldn´t you set up the automatic payments? 
which errors did you get?

what do you mean with reseting the pool? why does it take 3 days?

if you payout manual and then reset redis. what is the problem? 
i do not fully understand the question.

**Comment by theraw** [comment]
>why couldn´t you set up the automatic payments? 

i don't know it just won't work and this is not my first time with those i can't exactly show you outputs right now because has been a long time when i disabled automatic payments

>what do you mean with reseting the pool? why does it take 3 days?

like remove redis db restart server and start pool again. the "3 days" when the block is pending can i reset the pool like that? everything in redis will be lost so what will happen with pending blocks? so i've wait by leaving just 1 worker to mine

>if you payout manual and then reset redis. what is the problem?

this is what i'm doing so you got the question

>i do not fully understand the question.

I was asking if there is a way to mark the payment as paid in redis manually, 
example i pay everyone every 24 hours or 48h manually, when i do payments i reset the pool like starting from the begin no hash no blocks no pending balance everything 0. but i think this is not good.
also ppl somehow can find the pool and can see from website no payments and they can think that i'm stealing from miners. meanwhile only those who has mine know that they get paid..
ofcourse when i say "making the payments as paid manually in redis" it means i will also add Transaction id for every payment!

the problem is i haven't use redis i know nothing about it i was trying to find out how to do this but no success till now so i decided to ask here maybe someone can help if not no problem.
