### ISSUE TITLE
Where i can find in CryptoNoteConfig.h the Coin constant? 

### ISSUE THREAD

**Issue by blueavenue** [forknote/forknote-pool#70]
Hello,

is the field coinunits in the pool config.json important for correct pool working?

If yes:

Where i can find my Coin constant in the CryptNoteConfig.h?

Please help

**Comment by devduke** [comment]
Did you figure this out? Trying to find an answer to this as well.

**Comment by blueavenue** [comment]
Yes, i figured this out by using the miner on local host and simplewallet. The wallet shown me the right coinunit (with the coin decimal point). I edited then in the config.json.
