### ISSUE TITLE
Orphan

### ISSUE THREAD

**Issue by droidcoinio** [forknote/forknote-pool#75]
Hi, everyone. My NXB pool ( yes, another cryptonote-based coin ) has some very strange problem... 😂   The pool thinks all the blocks we found are orphan. However, only the last one is a real orphan block. Other blocks are just fine. Have you ever see this problem? http://youpool.io/NXB/#pool_blocks Now, I have to manually send the coins to the miner... Do you have some methods to  "undo" the orphan? I mean, change some entries in the Redis database to make the pool think those blocks are normal? Thanks! 👍

**Comment by pmitchev** [comment]
You are experiencing this:
https://github.com/forknote/forknote-pool/issues/48

**Comment by miningapps** [comment]
@droidcoinio  did you figure out how to recover the orphaned blocks?
