### ISSUE TITLE
Why all blocks mined are orphaned ?

### ISSUE THREAD

**Issue by miningapps** [forknote/forknote-pool#76]
I am testing this software and I sent some hash power to give it a try and it looks like all 3 blocks it found were orphaned?  That doesn't sound right...

http://bcn.jedipool.com/#pool_blocks

Thanks!

**Comment by pmitchev** [comment]
https://github.com/forknote/forknote-pool/issues/48

**Comment by pmitchev** [comment]
Soon this issue will be fixed

**Comment by miningapps** [comment]
Are the blocks recoverable? Do you know a link for patching this? Thanks!

**Comment by miningapps** [comment]
Fixed using the resolution from #48 

blockUnlocker.js from
apiInterfaces.rpcDaemon('getblockheaderbyheight', {height: block.height}, function(error, result){
to
apiInterfaces.rpcDaemon('getblockheaderbyheight', {height: block.height + 1}, function(error, result){

**Comment by 0xA01** [comment]
The same error
